#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Illacme-plenipes - Theme Schema and Custom Options Sovereignty Unit Tests
模块职责：验证自描述配置协议加载、合并自愈引擎，以及视觉选项和 GitHub 社交按钮在模版渲染中的无侵入物理注入。
🛡️ [V80.0]：主题配置热插拔与表单热配置里程碑演测。
"""

import unittest
from core.config.models.theme import ThemeSettings
from themes.sovereign.adapters.sovereign import SovereignSSGAdapter

class TestThemeSchemaSovereignty(unittest.TestCase):

    def test_schema_loading_integrity(self):
        """🚀 验证 BaseSSGAdapter 能够正确从 themes/sovereign 物理探测并加载 theme.schema.json 契约"""
        settings = ThemeSettings(name="sovereign", renderer="sovereign")
        adapter = SovereignSSGAdapter(theme_settings=settings)
        
        self.assertIsNotNone(adapter.theme_schema)
        self.assertEqual(adapter.theme_schema.get("title"), "Sovereign Theme Schema")
        
        properties = adapter.theme_schema.get("properties", {})
        self.assertIn("site_name", properties)
        self.assertIn("accent_color", properties)
        self.assertIn("enable_glassmorphism", properties)
        self.assertIn("github_repo", properties)
        
        # 验证各自默认值对齐
        self.assertEqual(properties["site_name"]["default"], "Illacme Sovereign")
        self.assertEqual(properties["accent_color"]["default"], "#00f5ff")
        self.assertEqual(properties["enable_glassmorphism"]["default"], True)
        self.assertEqual(properties["github_repo"]["default"], "")

    def test_options_merge_and_healing(self):
        """🚀 验证 get_custom_options() 的自愈深度合并引擎"""
        # 情况 1：未提供任何自定义 options，自动回退使用 schema 默认值
        settings_empty = ThemeSettings(name="default", renderer="sovereign", options={})
        adapter_empty = SovereignSSGAdapter(theme_settings=settings_empty)
        opts_empty = adapter_empty.get_custom_options()
        
        self.assertEqual(opts_empty["site_name"], "Illacme Sovereign")
        self.assertEqual(opts_empty["accent_color"], "#00f5ff")
        self.assertEqual(opts_empty["enable_glassmorphism"], True)
        self.assertEqual(opts_empty["github_repo"], "")

        # 情况 2：部分定制，其余字段自愈填充默认值
        custom_opts = {
            "site_name": "指挥官的数字花园",
            "accent_color": "#ff007f",
            "github_repo": "https://github.com/command/garden"
        }
        settings_partial = ThemeSettings(name="default", renderer="sovereign", options=custom_opts)
        adapter_partial = SovereignSSGAdapter(theme_settings=settings_partial)
        opts_partial = adapter_partial.get_custom_options()
        
        self.assertEqual(opts_partial["site_name"], "指挥官的数字花园")
        self.assertEqual(opts_partial["accent_color"], "#ff007f")
        self.assertEqual(opts_partial["enable_glassmorphism"], True) # 未配置，自愈回退 True
        self.assertEqual(opts_partial["github_repo"], "https://github.com/command/garden")

    def test_rendering_injection_and_aesthetic_healing(self):
        """🚀 验证模板渲染过程中站点名称、发光色、毛玻璃开关及 GitHub 链接的完美注入"""
        custom_opts = {
            "site_name": "主权赛博空间",
            "accent_color": "#ffaa00",
            "enable_glassmorphism": False,
            "github_repo": "https://github.com/illacme/plenipes"
        }
        settings = ThemeSettings(name="default", renderer="sovereign", options=custom_opts)
        adapter = SovereignSSGAdapter(theme_settings=settings)
        
        body = "# 标题\n这是正文内容。"
        fm = {"title": "我的第一篇文档", "route_prefix": "docs"}
        
        html_out, _ = adapter.render(body, fm, target_lang="zh", sub_path="docs/intro.html")
        
        # 1. 验证 site_name 正确物理渲染替换
        self.assertIn("<title>我的第一篇文档 | 主权赛博空间</title>", html_out)
        self.assertIn('<span class="logo-text">主权赛博空间</span>', html_out)
        self.assertIn("2026 主权赛博空间. All Rights Reserved. Generated by", html_out)
        
        # 2. 验证 custom_theme_styles (颜色与毛玻璃特效关闭样式) 精准注入
        self.assertIn("--accent-color: #ffaa00;", html_out)
        self.assertIn("--accent-glow: #ffaa0040;", html_out) # hex 发光透明度处理
        self.assertIn("backdrop-filter: none !important;", html_out) # 玻璃降级控制触发
        
        # 3. 验证 GitHub 社交挂载完美挂上
        self.assertIn('href="https://github.com/illacme/plenipes"', html_out)
        self.assertIn('class="social-icon-link github-btn"', html_out)
        self.assertIn('🐙</a>', html_out)

    def test_rendering_without_github_repo(self):
        """🚀 验证未配置 GitHub 仓库时，社交导航挂载占位符被静默清空"""
        settings = ThemeSettings(name="default", renderer="sovereign", options={})
        adapter = SovereignSSGAdapter(theme_settings=settings)
        
        body = "# 测试"
        fm = {"title": "无社交测试", "route_prefix": "docs"}
        
        html_out, _ = adapter.render(body, fm, target_lang="zh", sub_path="docs/intro.html")
        
        # GitHub 挂载按钮应该不存在
        self.assertNotIn("github-btn", html_out)

    def test_global_config_inherit_and_override(self):
        """🚀 [Unified Promotion] 验证全局配置提升后的继承、Fallback自愈与局部主题覆盖逻辑"""
        class MockConfig:
            def __init__(self):
                self.site_name = "我的全局主权站点"
                self.site_description = "全局系统治理与多语种出版"
                self.favicon_path = "/static/fav.ico"
                self.logo_path = "/static/unified-logo.png"
                self.frontmatter_defaults = {
                    "copyright": "© 2026 Sovereign Creator. All Rights Reserved."
                }
                self.i18n_settings = None

        class MockEngine:
            def __init__(self):
                self.config = MockConfig()

        mock_engine = MockEngine()

        # 🚀 Case 1: 纯粹继承全局配置 (零局部配置)
        settings_empty = ThemeSettings(name="default", renderer="sovereign", options={})
        adapter_empty = SovereignSSGAdapter(theme_settings=settings_empty, engine=mock_engine)
        opts_empty = adapter_empty.get_custom_options()

        self.assertEqual(opts_empty["site_name"], "我的全局主权站点")
        self.assertEqual(opts_empty["site_description"], "全局系统治理与多语种出版")
        self.assertEqual(opts_empty["favicon_path"], "/static/fav.ico")
        self.assertEqual(opts_empty["logo_path"], "/static/unified-logo.png")
        # 验证版权自愈回退继承 (from frontmatter_defaults.copyright)
        self.assertEqual(opts_empty["footer_copyright"], "© 2026 Sovereign Creator. All Rights Reserved.")

        # 🚀 Case 2: 局部配置覆盖全局配置 (主题选项优先级最高)
        custom_opts = {
            "site_name": "主题特殊重写标题",
            "footer_copyright": "© 2026 Theme Specific Copyright"
        }
        settings_override = ThemeSettings(name="default", renderer="sovereign", options=custom_opts)
        adapter_override = SovereignSSGAdapter(theme_settings=settings_override, engine=mock_engine)
        opts_override = adapter_override.get_custom_options()

        # 被局部选项成功覆盖的字段
        self.assertEqual(opts_override["site_name"], "主题特殊重写标题")
        self.assertEqual(opts_override["footer_copyright"], "© 2026 Theme Specific Copyright")
        # 未被局部选项覆盖、仍继承全局的字段
        self.assertEqual(opts_override["logo_path"], "/static/unified-logo.png")

    def test_default_imprint_license_sovereignty(self):
        """🚀 验证默认品牌 (default) 在初始未激活状态下统一标定为 LITE，且作为官方示范文库不占自建额度"""
        from core.governance.license_guard import LicenseGuard
        
        # 默认品牌状态下
        from core.governance.imprint_manager import im
        im.active_imprint = "default"
        LicenseGuard.clear_cache()
        self.assertEqual(LicenseGuard.get_active_tier(), "LITE")
        self.assertTrue(LicenseGuard.is_pro_feature_allowed("multi_language"))
        self.assertTrue(LicenseGuard.is_pro_feature_allowed("subfolder_ingress"))
        self.assertEqual(LicenseGuard.get_max_custom_imprints(), 1)
        self.assertEqual(LicenseGuard.get_max_imprints(), 2)
        self.assertEqual(LicenseGuard.get_max_i18n_targets(), 1)
        
        info = LicenseGuard.get_license_info()
        self.assertEqual(info["tier"], "LITE")
        self.assertEqual(info["tier_name"], "免费社区版")
        self.assertFalse(info["is_licensed"])

    def test_three_tier_quotas(self):
        """🚀 验证 3-Tier（LITE / STANDARD / PRO）配额分级体系与轻量化放行"""
        from core.governance.license_guard import LicenseGuard
        
        LicenseGuard.clear_cache()
        # Mock 基础增强版 (STANDARD)
        LicenseGuard._cached_license_result = (True, {"tier": "STANDARD", "customer": "标准版创作者"})
        
        self.assertEqual(LicenseGuard.get_active_tier(), "STANDARD")
        self.assertEqual(LicenseGuard.get_max_custom_imprints(), 5)
        self.assertEqual(LicenseGuard.get_max_imprints(), 6)
        self.assertEqual(LicenseGuard.get_max_i18n_targets(), 5)
        self.assertTrue(LicenseGuard.is_pro_feature_allowed("multi_language"))
        self.assertTrue(LicenseGuard.is_pro_feature_allowed("subfolder_ingress"))
        self.assertTrue(LicenseGuard.is_pro_feature_allowed("multi_dialect"))
        self.assertTrue(LicenseGuard.is_pro_feature_allowed("cloud_harvesting"))
        
        info = LicenseGuard.get_license_info()
        self.assertEqual(info["tier"], "STANDARD")
        self.assertEqual(info["tier_name"], "基础增强版")
        self.assertEqual(info["max_custom_imprints"], 5)
        self.assertEqual(info["max_imprints"], 6)
        self.assertEqual(info["max_i18n_targets"], 5)
        
        LicenseGuard.clear_cache()

if __name__ == "__main__":
    unittest.main()
