#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Illacme-plenipes Core - Language Metadata Data Shim (全球语种元数据垫片)
职责：承载官方支持的语种大盘矩阵与反向语种映射表，缓解 language_hub.py 物理规模压力。
"""

# 🚀 [V55.4] 官方支持的语种矩阵 (前 50 大语种，带元数据与图标)
SUPPORTED_MATRIX = [
    {"code": "zh", "name": "简体中文", "icon": "🇨🇳"},
    {"code": "en", "name": "English", "icon": "🇬🇧"},
    {"code": "hi", "name": "हिन्दी", "icon": "🇮🇳"},
    {"code": "es", "name": "Español", "icon": "🇪🇸"},
    {"code": "fr", "name": "Français", "icon": "🇫🇷"},
    {"code": "ar", "name": "العربية", "icon": "🇸🇦"},
    {"code": "bn", "name": "বাংলা", "icon": "🇧🇩"},
    {"code": "pt", "name": "Português", "icon": "🇵🇹"},
    {"code": "ru", "name": "Русский", "icon": "🇷🇺"},
    {"code": "ur", "name": "اردو", "icon": "🇵🇰"},
    {"code": "id", "name": "Bahasa Indonesia", "icon": "🇮🇩"},
    {"code": "de", "name": "Deutsch", "icon": "🇩🇪"},
    {"code": "ja", "name": "日本語", "icon": "🇯🇵"},
    {"code": "mr", "name": "मराठी", "icon": "🇮🇳"},
    {"code": "te", "name": "తెలుగు", "icon": "🇮🇳"},
    {"code": "tr", "name": "Türkçe", "icon": "🇹🇷"},
    {"code": "ta", "name": "தமிழ்", "icon": "🇮🇳"},
    {"code": "vi", "name": "Tiếng Việt", "icon": "🇻🇳"},
    {"code": "tl", "name": "Tagalog", "icon": "🇵🇭"},
    {"code": "ko", "name": "한국어", "icon": "🇰🇷"},
    {"code": "fa", "name": "فارسی", "icon": "🇮🇷"},
    {"code": "ha", "name": "Hausa", "icon": "🇳🇬"},
    {"code": "sw", "name": "Kiswahili", "icon": "🇰🇪"},
    {"code": "jv", "name": "Javanese", "icon": "🇮🇩"},
    {"code": "it", "name": "Italiano", "icon": "🇮🇹"},
    {"code": "pa", "name": "ਪੰਜਾਬੀ", "icon": "🇵🇰"},
    {"code": "kn", "name": "ಕನ್ನಡ", "icon": "🇮🇳"},
    {"code": "gu", "name": "ગુજરાતી", "icon": "🇮🇳"},
    {"code": "th", "name": "ไทย", "icon": "🇹🇭"},
    {"code": "am", "name": "አማርኛ", "icon": "🇪🇹"},
    {"code": "yo", "name": "Yorùbá", "icon": "🇳🇬"},
    {"code": "my", "name": "မြန်မာဘာသာ", "icon": "🇲🇲"},
    {"code": "om", "name": "Oromoo", "icon": "🇪🇹"},
    {"code": "ps", "name": "پښتو", "icon": "🇦🇫"},
    {"code": "uk", "name": "Українська", "icon": "🇺🇦"},
    {"code": "su", "name": "Basa Sunda", "icon": "🇮🇩"},
    {"code": "pl", "name": "Polski", "icon": "🇵🇱"},
    {"code": "uz", "name": "Oʻzbekcha", "icon": "🇺🇿"},
    {"code": "ro", "name": "Română", "icon": "🇷🇴"},
    {"code": "az", "name": "Azərbaycanca", "icon": "🇦🇿"},
    {"code": "ml", "name": "മലയാളം", "icon": "🇮🇳"},
    {"code": "sd", "name": "سنڌي", "icon": "🇵🇰"},
    {"code": "ig", "name": "Igbo", "icon": "🇳🇬"},
    {"code": "hu", "name": "Magyar", "icon": "🇭🇺"},
    {"code": "el", "name": "Ελληνικά", "icon": "🇬🇷"},
    {"code": "cs", "name": "Čeština", "icon": "🇨🇿"},
    {"code": "nl", "name": "Nederlands", "icon": "🇳🇱"},
    {"code": "sv", "name": "Svenska", "icon": "🇸🇪"},
    {"code": "fi", "name": "Suomi", "icon": "🇫🇮"},
    {"code": "no", "name": "Norsk", "icon": "🇳🇴"}
]

# 🚀 [V10.2] 反向解析字典：ISO -> 友好名称名称
REVERSE_MAP = {
    "zh": "Chinese (Simplified)",
    "zh-Hant": "Chinese (Traditional)",
    "en": "English",
    "ja": "Japanese",
    "fr": "French",
    "de": "German",
    "es": "Spanish",
    "it": "Italian",
    "ko": "Korean",
    "ru": "Russian",
    "hi": "Hindi",
    "ar": "Arabic",
    "bn": "Bengali",
    "pt": "Portuguese",
    "ur": "Urdu",
    "id": "Indonesian",
    "tr": "Turkish",
    "vi": "Vietnamese",
    "th": "Thai",
    "pl": "Polish",
    "uk": "Ukrainian",
    "nl": "Dutch",
    "sv": "Swedish",
    "no": "Norwegian",
    "fi": "Finnish",
    "el": "Greek",
    "cs": "Czech",
    "hu": "Hungarian",
    "mr": "Marathi",
    "te": "Telugu",
    "ta": "Tamil",
    "tl": "Tagalog",
    "fa": "Persian",
    "ha": "Hausa",
    "sw": "Swahili",
    "jv": "Javanese",
    "pa": "Punjabi",
    "kn": "Kannada",
    "gu": "Gujarati",
    "am": "Amharic",
    "yo": "Yoruba",
    "my": "Burmese",
    "om": "Oromo",
    "ps": "Pashto",
    "su": "Sundanese",
    "uz": "Uzbek",
    "ro": "Romanian",
    "az": "Azerbaijani",
    "ml": "Malayalam",
    "sd": "Sindhi",
    "ig": "Igbo"
}
